### ISSUE TITLE
Trouble linking JS an JQuery...??

### ISSUE THREAD

**Issue by cherryBotha** [cherryBotha/jumpstart#1]
I'm having trouble getting my JS and Jquery to work, I think the problem is on line 149 - 151.

`<script src="https://code.jquery.com/jquery-3.2.1.min.js"integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="crossorigin="anonymous"></script>
<script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.6.0/slick.min.js"></script>
<script type="text/javascript" src="./resources/js/main.js"></script>`

**Comment by irmandos** [comment]
Check Pull Request #2 for possible fix

**Comment by irmandos** [comment]
Check pull request #3
